export default [
  'Aegean Airlines',
  'Aer Lingus',
  'Aeroflot',
  'Aerolineas Argentinas',
  'Aeromexico',
  'Air Canada',
  'Air China',
  'Air Europa',
  'Air France',
  'Air India',
  'Air India Express',
  'Air New Zealand',
  'Air Serbia',
  'Air Tahiti Nui',
  'Air Transat',
  'Air Vanuatu',
  'AirAsia',
  'AirAsia X',
  'airberlin',
  'Alaska Airlines',
  'Alitalia',
  'Allegiant',
  'American Airlines',
  'ANA',
  'Asiana',
  'AtlasGlobal',
  'Austrian',
  'Avianca',
  'Azul',
  'Bangkok Airways',
  'British Airways',
  'Brussels Airlines',
  'Cathay Pacific',
  'CEBU Pacific Air',
  'China Airlines',
  'China Eastern',
  'China Southern',
  'Condor',
  'Copa Airlines',
  'Czech Airlines',
  'Delta',
  'Dragonair',
  'easyJet',
  'Edelweiss Air',
  'EL AL',
  'Emirates',
  'Ethiopian Airlines',
  'Etihad',
  'Eurowings',
  'EVA Air',
  'Fiji Airways',
  'Finnair',
  'FlyBE',
  'Frontier',
  'Garuda Indonesia',
  'Germanwings',
  'Gol',
  'Gulf Air',
  'Hainan Airlines',
  'Hawaiian Airlines',
  'Iberia',
  'Icelandair',
  'IndiGo Airlines',
  'InterJet',
  'Japan Airlines',
  'Jet Airways',
  'JetBlue',
  'Jetstar',
  'Kenya Airways',
  'KLM',
  'Korean Air',
  'LATAM Brasil',
  'LATAM Chile',
  'Lion Airlines',
  'LOT Polish Airlines',
  'Lufthansa',
  'Malaysia Airlines',
  'Monarch',
  'Nok Air',
  'Norwegian Air Shuttle',
  'Oman Air',
  'OpenSkies',
  'Peach',
  'Philippine Airlines',
  'Porter',
  'Qantas',
  'Qatar Airways',
  'Regional Express',
  'Royal Air Maroc',
  'Royal Brunei',
  'Royal Jordanian',
  'Ryanair',
  'S7 Airlines',
  'SAS',
  'Saudia',
  'Scoot Airlines',
  'Silkair',
  'Singapore Airlines',
  'Skylanes',
  'South African Airways',
  'Southwest',
  'SpiceJet',
  'Spirit',
  'Spring Airlines',
  'Spring Japan',
  'SriLankan Airlines',
  'Sun Country',
  'SWISS',
  'TACA',
  'TAP Portugal',
  'THAI',
  'Thomas Cook Airlines',
  'Thomson',
  'tigerair',
  'tigerair Australia',
  'TUIfly',
  'Turkish Airlines',
  'United',
  'Vanilla Air',
  'Vietnam Airlines',
  'Virgin America',
  'Virgin Atlantic',
  'Virgin Australia',
  'Volaris',
  'Vueling Airlines',
  'WestJet',
  'Wizzair',
  'WOW air',
  'Xiamen Airlines',
];
